### ISSUE TITLE
"Version constraint v2.9.0 is not supported."

### ISSUE THREAD

**Issue by gvl-software-entwicklung** [phar-io/phive#104]
It seems like phive doesn't like versions with leading `v`. Although it install `phpdocumentor` initially it doesn't like to install it from `phive.xml` afterwards.

See output below.

To reproduce:

Summary: `phive install && phive install phpdocumentor && phive install`

```
$ phive install
Phive 0.6.3 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phive.xml
Linking phpunit-6.1.0.phar to ./tools/phpunit
Downloading https://phar.phpunit.de/phive.xml
Linking phpcpd-3.0.0.phar to ./tools/phpcpd

$ phive install phpdocumentor
Phive 0.6.3 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpdocumentor/phpdocumentor2/releases
Linking phpDocumentor.phar to /home/krebs/Workspace/Shared/CoreDBBundle/tools/phpDocumentor

$ phive install              
Phive 0.6.3 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    An error occurred while processing your request:

          Version constraint ^v2.9.0 is not supported.
          
          #0 har:///usr/share/webapps/bin/phive.phar/vendor/phar-io/version/src/VersionConstraintParser.php(28)
          #1 har:///usr/share/webapps/bin/phive.phar/src/shared/config/PhiveXmlConfig.php(168): PharIo\Version\VersionConstraintParser->parse()
          #2 har:///usr/share/webapps/bin/phive.phar/src/commands/install/InstallCommandConfig.php(67): PharIo\Phive\PhiveXmlConfig->getPhars()
          #3 har:///usr/share/webapps/bin/phive.phar/src/commands/install/InstallCommandConfig.php(56): PharIo\Phive\InstallCommandConfig->getPharsFromPhiveXmlConfig()
          #4 har:///usr/share/webapps/bin/phive.phar/src/commands/install/InstallCommand.php(49): PharIo\Phive\InstallCommandConfig->getRequestedPhars()
          #5 har:///usr/share/webapps/bin/phive.phar/src/shared/cli/Runner.php(204): PharIo\Phive\InstallCommand->execute()
          #6 har:///usr/share/webapps/bin/phive.phar/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #7 usr/share/webapps/bin/phive.phar(212): PharIo\Phive\Cli\Runner->run()
          #8 {main}

          Environment: PHP 7.1.5
          Phive Version: 0.6.3

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

`phive.xml` before and afterwards

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="phpunit" version="^6.0.0" installed="6.1.0" location="./tools/phpunit"/>
  <phar name="phpcpd" version="^3.0.0" installed="3.0.0" location="./tools/phpcpd"/>
</phive>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="phpunit" version="^6.0.0" installed="6.1.0" location="./tools/phpunit"/>
  <phar name="phpcpd" version="^3.0.0" installed="3.0.0" location="./tools/phpcpd"/>
  <phar name="phpdocumentor" version="^v2.9.0" installed="v2.9.0" location="./tools/phpDocumentor"/>
</phive>
```

I've tried to change `version` and `installed` manually, but then `phive` cannot find the package anymore,

**Comment by belanur** [comment]
Thanks for reporting the issue! We will include support for this in the upcoming version 0.7.0.
