### ISSUE TITLE
 Call to a member function format() on null

### ISSUE THREAD

**Issue by theseer** [phar-io/phive#130]
Installing with --trust-keys crashes
```
phive install --trust-gpg-keys 4AA394086372C20A,2A8299CE842DD38C


Phive 0.9.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching respository list
Downloading https://phar.io/data/repositories.xml
Downloading https://phar.phpunit.de/phive.xml
Downloading https://phar.phpunit.de/phpunit-6.5.6.phar
Downloading https://phar.phpunit.de/phpunit-6.5.6.phar.asc
Downloading key 4AA394086372C20A
Trying https://hkps.pool.sks-keyservers.net
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=get&options=mr
Successfully downloaded key
[ERROR]    An error occurred while processing your request:

          Call to a member function format() on null
          
          #0 src/services/key/PublicKey.php(68)
          #1 src/services/key/KeyService.php(69): PharIo\Phive\PublicKey->getInfo()
          #2 src/services/signature/gpg/GnupgSignatureVerifier.php(40): PharIo\Phive\KeyService->importKey()
          #3 src/services/phar/PharDownloader.php(109): PharIo\Phive\GnupgSignatureVerifier->verify()
          #4 src/services/phar/PharDownloader.php(61): PharIo\Phive\PharDownloader->verifySignature()
          #5 src/services/phar/PharService.php(38): PharIo\Phive\PharDownloader->download()
          #6 src/services/phar/InstallService.php(67): PharIo\Phive\PharService->getPharFromRelease()
          #7 src/commands/install/InstallCommand.php(58): PharIo\Phive\InstallService->execute()
          #8 src/commands/install/InstallCommand.php(44): PharIo\Phive\InstallCommand->installRequestedPhar()
          #9 src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #10 src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #11 phive(54): PharIo\Phive\Cli\Runner->run()
          #12 {main}

          Environment: PHP 7.2.2
          Phive Version: 0.9.0

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by theseer** [comment]
It does not seem to happen for every run.

**Comment by theseer** [comment]
The only way this can happen is that the response from the keyserver, despite it claiming to be successful, was not actually containing the data the parser expects. That would lead to non of the cases in `PublicKey::parseInfo()` matching and `$this->created` not being set.

Not sure how to fix that the right way (tm).

**Comment by theseer** [comment]
Work on this should continue in #147.
