### ISSUE TITLE
Version constraint ^3.0.0-alpha1 is not supported.

### ISSUE THREAD

**Issue by sebastianbergmann** [phar-io/phive#145]
```
$ phive install phing
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Linking /home/sb/.phive/phars/phing-3.0.0-alpha1.phar to /home/sb/example/tools/phing
```
```
$ cat phive.xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="phing" version="^3.0.0-alpha1" installed="3.0.0-alpha1" location="./tools/phing"/>
</phive>
```
```
$ phive update
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    An error occurred while processing your request:

          Version constraint ^3.0.0-alpha1 is not supported.
          
          #0 har:///usr/local/bin/phive/vendor/phar-io/version/src/VersionConstraintParser.php(28)
          #1 har:///usr/local/bin/phive/src/shared/config/PhiveXmlConfig.php(239): PharIo\Version\VersionConstraintParser->parse()
          #2 har:///usr/local/bin/phive/src/shared/config/PhiveXmlConfig.php(188): PharIo\Phive\PhiveXmlConfig->nodeToConfiguredPhar()
          #3 har:///usr/local/bin/phive/src/commands/update/UpdateCommandConfig.php(68): PharIo\Phive\PhiveXmlConfig->getPhars()
          #4 har:///usr/local/bin/phive/src/commands/update/UpdateCommandConfig.php(44): PharIo\Phive\UpdateCommandConfig->getPharAliasesFromPhiveXmlConfig()
          #5 har:///usr/local/bin/phive/src/commands/update/UpdateCommand.php(45): PharIo\Phive\UpdateCommandConfig->getRequestedPhars()
          #6 har:///usr/local/bin/phive/src/shared/cli/Runner.php(211): PharIo\Phive\UpdateCommand->execute()
          #7 har:///usr/local/bin/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #8 usr/local/bin/phive(300): PharIo\Phive\Cli\Runner->run()
          #9 {main}

          Environment: PHP 7.2.6
          Phive Version: 0.10.0

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by filips123** [comment]
Installation also doesn't work for versions like `3.0.0-beta.4` (with a dot between beta and 4).

**Comment by belanur** [comment]
This has been fixed in [phar-io/version 2.0.0](https://github.com/phar-io/version/releases/tag/2.0.0). The next release of Phive will use this version. 

While comparing alpha and beta versions will work as expected, it may not be desirable to install pre-release versions of tools unless explicitly requested. This has not been addressed yet.

**Comment by filips123** [comment]
When will be next release published?

**Comment by theseer** [comment]
Closing this.

Support for a given stability level will be tracked in it's own ticket:  #154
