### ISSUE TITLE
Installation from URL doesn't work for some URLs

### ISSUE THREAD

**Issue by filips123** [phar-io/phive#149]
## Installation of unsigned PHARs

Installation from URLs which doesn't have `.asc` file will fail. PHIVE should allow user to install unsigned PHARs, but with warning.

For example, if I try to install Composer 1.6.5., I get 404 error for file `composer.phar.asc`.

```
$ sudo phive install -g https://github.com/composer/composer/releases/download/1.6.0/composer.phar
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://github.com/composer/composer/releases/download/1.6.0/composer.phar
[ERROR]    Failed to download load https://github.com/composer/composer/releases/download/1.6.0/composer.phar.asc: HTTP Code 404
```

## Installation of PHARs with pre-release suffixes (already in #145)

I want to install `humbug/box` 3.0.0 Beta 4 (`3.0.0-beta.4`). I can't install it, because I get error.

```
$ sudo phive install -g https://github.com/humbug/box/releases/download/3.0.0-beta.4/box.phar
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    An error occurred while processing your request:

          Version string '3.0.0-beta.4' does not follow SemVer semantics

          #0 har:///usr/local/bin/phive/vendor/phar-io/version/src/Version.php(155)
          #1 har:///usr/local/bin/phive/vendor/phar-io/version/src/Version.php(43): PharIo\Version\Version->ensureVersionStringIsValid()
          #2 har:///usr/local/bin/phive/src/shared/phar/PharUrl.php(35): PharIo\Version\Version->__construct()
          #3 har:///usr/local/bin/phive/src/commands/install/InstallCommandConfig.php(119): PharIo\Phive\PharUrl->getPharVersion()
          #4 har:///usr/local/bin/phive/src/commands/install/InstallCommandConfig.php(76): PharIo\Phive\InstallCommandConfig->getPharsFromCliArguments()
          #5 har:///usr/local/bin/phive/src/commands/install/InstallCommand.php(43): PharIo\Phive\InstallCommandConfig->getRequestedPhars()
          #6 har:///usr/local/bin/phive/src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #7 har:///usr/local/bin/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #8 usr/local/bin/phive(300): PharIo\Phive\Cli\Runner->run()
          #9 {main}

          Environment: PHP 7.2.6-1+ubuntu16.04.1+deb.sury.org+1
          Phive Version: 0.10.0

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by filips123** [comment]
Similar issue has been already opened: #145

**Comment by theseer** [comment]
Duplicates of #134 and #145, respectively.
