### ISSUE TITLE
Directory "U:\" creation error on phploc installation on Windows

### ISSUE THREAD

**Issue by mjawaids** [phar-io/phive#172]
When trying to install phploc v2.1.3 it gives error about creating "U:\" directory while there is no such drive/directory available on the system. Below is the command I'm running and error I'm getting.

```
D:\>php phive-0.12.0.phar install phploc@~2.1.3
Phive 0.12.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]   An error occurred while processing your request:

          Creating directory "U:\" failed.

          #0 har://D:/phive-0.12.0.phar/vendor/phar-io/filesystem/src/Directory.php(100)
          #1 har://D:/phive-0.12.0.phar/vendor/phar-io/filesystem/src/Directory.php(24): PharIo\FileSystem\Directory->ensureExists()
          #2 har://D:/phive-0.12.0.phar/src/shared/environment/WindowsEnvironment.php(24): PharIo\FileSystem\Directory->__construct()
          #3 har://D:/phive-0.12.0.phar/src/shared/config/Config.php(49): PharIo\Phive\WindowsEnvironment->getHomeDirectory()
          #4 har://D:/phive-0.12.0.phar/src/Factory.php(382): PharIo\Phive\Config->getHomeDirectory()
          #5 har://D:/phive-0.12.0.phar/src/Factory.php(279): PharIo\Phive\Factory->getPharRegistry()
          #6 har://D:/phive-0.12.0.phar/src/Factory.php(127): PharIo\Phive\Factory->getInstallService()
          #7 har://D:/phive-0.12.0.phar/src/commands/CommandLocator.php(40): PharIo\Phive\Factory->getInstallCommand()
          #8 har://D:/phive-0.12.0.phar/src/shared/cli/Runner.php(211): PharIo\Phive\CommandLocator->getCommand()
          #9 har://D:/phive-0.12.0.phar/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #10 :\phive-0.12.0.phar(306): PharIo\Phive\Cli\Runner->run()
          #11 {main}

          Environment: PHP 7.1.14
          Phive Version: 0.12.0

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

I also tried below but to no use:
D:\>php phive-0.12.0.phar install phploc@2.1.3

**Comment by theseer** [comment]
While I agree that `phive` shouldn't crash on this, the problem is a broken environment setup on your end.

The HOME directory in your terminal session is set to "U:\", which obviously doesn't exist and for obvious reasons can not be created either.

**Comment by mjawaids** [comment]
How come HOME directory is set to something that doesn't exist and how to fix it? Appreciate your help.

**Comment by theseer** [comment]
I'm not sure we/I can help here as that's a configuration on your windows system.

Traditionally, on operating systems that work with drive letters (like windows) use
the drive letter U: for network based home directories - potentially having picked U for User. That of course only when actually being connected to the network.

From within Phive, we only _read_ the HOME directory setting from the environment. In windows this are HOMEDRIVE and HOMEPATH environment variables. Code can be found [here](https://github.com/phar-io/phive/blob/a563fea61e560589613b4e80c5e089143a267215/src/shared/environment/WindowsEnvironment.php#L12) and [here](https://github.com/phar-io/phive/blob/a563fea61e560589613b4e80c5e089143a267215/src/shared/environment/WindowsEnvironment.php#L24). We do not have any control over these values.

**Comment by cautionbug** [comment]
i wasn't willing to accept a hard-coded internal path setup inside the phar code.  
For what it's worth (keeping in mind it's 4am)...

i'm using Windows, and i worked my way around the `HOME*` variables within a .bat file (attached, just switch `.txt` to `.bat`). Temporarily changing the variables Phive assumes will attempt to install the packages there.

Unfortunately, #208 is preventing me from getting any packages successfully installed to confirm if this ***actually*** works, but i do see the `.phive` and `tools` directories get created in the intended target, so that's a good sign.

Another benefit is you can add the BAT's directory to `%PATH%` and call `phive ...` as a typical command.

i follow this pattern for several other phar tools (composer, pear/pecl, phpcs, etc.) and so far so good, as brittle as my BAT code is... Should be easy enough to build parallels for a Linux environment.

[phive.txt](https://github.com/phar-io/phive/files/3782220/phive.txt)

**Comment by theseer** [comment]
You realize you can just as well specify an alternative home directory by simply suppling `--home` as a parameter to phive, right?

I'm not sure though, what you are trying to fix here?

**Comment by evs-xsarus** [comment]
@theseer that doesn't work sadly :

```
evs@XSA-LT2020003:~/sites/dlk_upgrade/current/qa (preview/staging3) $ p81 phive.phar --home /tmp
[ERROR]    An error occurred while processing your request:

          Creating directory "/home/dockeruser/.phive" failed.
          
          #0 vendor/phar-io/filesystem/src/Directory.php(67)
          #1 src/shared/config/Config.php(64): PharIo\FileSystem\Directory->ensureExists()
          #2 src/services/migration/HomePharsXmlMigration.php(24): PharIo\Phive\Config->getHomeDirectory()
          #3 src/services/migration/MigrationFactory.php(30): PharIo\Phive\HomePharsXmlMigration->__construct()
          #4 src/services/migration/MigrationService.php(28): PharIo\Phive\MigrationFactory->getMigrations()
          #5 src/shared/cli/Runner.php(198): PharIo\Phive\MigrationService->ensureFitness()
          #6 src/shared/cli/Runner.php(93): PharIo\Phive\Cli\Runner->ensureFitness()
          #7 (354): PharIo\Phive\Cli\Runner->run()
          #8 {main}

          Environment: PHP 8.1.1 (on Linux 5.13.0-51-generic)
          Phive Version: 0.15.1

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by cweiske** [comment]
I still have the same problem with phive 0.15.3:
```
$ phive --home /var/www/webapp/.phive/
[ERROR]    An error occurred while processing your request:

          Creating directory "/var/www/.phive" failed.
```

**Comment by theseer** [comment]
I cannot reproduce this:

```
theseer@nyda /tmp/x9 $ ll home

total 16
drwx------. 3 theseer theseer   120 11. Dez 15:57 gpg
drwx------. 4 theseer theseer    80 11. Dez 15:57 http-cache
drwxr-xr-x. 2 theseer theseer    60 11. Dez 15:57 phars
-rw-r--r--. 1 theseer theseer   382 11. Dez 15:57 registry.xml
-rw-r--r--. 1 theseer theseer 10053 11. Dez 15:57 repositories.xml
drwx------. 3 theseer theseer    60 11. Dez 15:57 _tmp_wrk

theseer@nyda /tmp/x9 $ which phive
/usr/bin/phive

theseer@nyda /tmp/x9 $ php84 `which phive` --home /tmp/x9/home install phpab

Phive 0.15.3 - Copyright (C) 2015-2024 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching repository list
Downloading https://phar.io/data/repositories.xml
Downloading https://api.github.com/repos/theseer/autoload/releases?per_page=100
Downloading https://github.com/theseer/Autoload/releases/download/1.29.3/phpab-1.29.3.phar
Downloading https://github.com/theseer/Autoload/releases/download/1.29.3/phpab-1.29.3.phar.asc
Downloading key 2A8299CE842DD38C
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x2A8299CE842DD38C
Successfully downloaded key.

	Fingerprint: BEEB 9AED 51C2 8445 FAB1 4222 8DDB 46C4 EA2E BCDC

	Arne Blankerts <Arne@Blankerts.de>

	Created: 2009-03-14

Import this key? [y|N] y
Linking /tmp/x9/home/phars/phpab-1.29.3.phar to /tmp/x9/tools/phpab
```

Works like charm?

**Comment by cweiske** [comment]
In my case `/var/www` is not owned by `www-data`, and thus the `www-data`-user cannot create the `.phive/` configuration directory.

**Comment by theseer** [comment]
So, what do you expect phive to do in such a case? It clearly cannot operate. I agree that we might "crash" in a more clean fashion, but the result is the same..

**Comment by cweiske** [comment]
I specify `--home`, but phive still wants to create a different directory. This seems to be the culprit.

**Comment by theseer** [comment]
With `--home` you specify where the *home* directory is (hence the name ;-).

What fails here is the creation of the local project specific storage directory. There currently is no switch to have that stored outside of the project.

Phive has three directories it uses by default:
- The home directory (defaults to `$HOME/.phive`, can be overwritten by `--home`) where it keeps track of repositories, gpg keys and phars already downloaded and where they are used. This is shared among projects and is the source of the symlink for the phars.
- The `.phive` directory within the project where the phars.xml is stored, and additional files like `auth.xml` may be located
- The `tools` directory, where - by default at least - the phars are symlinked into - or copied, in case `--copy` is given

Phive for obvious reasons requires write access to all 3 locations.

**Comment by cweiske** [comment]
No, it's the home directory override that does not work. To verify, set the HOME variable to a non-writable directory and then pass the `--home` option, which should override the HOME environment variable:
```
$ HOME=/ phive --home /var/www/.phive
[ERROR]    An error occurred while processing your request:

          Creating directory "//.phive" failed.
```
