### ISSUE TITLE
SemVer error when installing Phing

### ISSUE THREAD

**Issue by jawira** [phar-io/phive#173]
Hello, I get an error when I try to install `Phing`. 

I know the error message tells that `7.2.10-0ubuntu0.18.04.1` is an invalid SemVer number, but I don't have any issue when installing other phar (`phpunit`, `phpstan`). Maybe this is due to Phing's version `phing-3.0.0-alpha1` ?

The output:

```
$ phive install phing
Phive 0.12.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phingofficial/phing/releases
Downloading https://github.com/phingofficial/phing/releases/download/3.0.0-alpha1/phing-3.0.0-alpha1.phar
Downloading https://github.com/phingofficial/phing/releases/download/3.0.0-alpha1/phing-3.0.0-alpha1.phar.asc
Downloading key 2420BAE0A3BE25C6
Trying hkps.pool.sks-keyservers.net (192.146.137.99)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x2420BAE0A3BE25C6&op=index&options=mr
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x2420BAE0A3BE25C6&op=get&options=mr
Successfully downloaded key

        Fingerprint: 566E 877A 27BD 4343 E956 BC9D 2420 BAE0 A3BE 25C6

        Michiel Rook <mrook@php.net> (2012-04-06)

        Created: 2012-04-06

Import this key? [y|N] y
[ERROR]    An error occurred while processing your request:

          Version string '7.2.10-0ubuntu0.18.04.1' does not follow SemVer semantics
          
          #0 har:///usr/bin/phive/vendor/phar-io/version/src/Version.php(168)
          #1 har:///usr/bin/phive/vendor/phar-io/version/src/Version.php(43): PharIo\Version\Version->ensureVersionStringIsValid()
          #2 har:///usr/bin/phive/src/services/phar/CompatibilityService.php(53): PharIo\Version\Version->__construct()
          #3 har:///usr/bin/phive/src/services/phar/InstallService.php(69): PharIo\Phive\CompatibilityService->canRun()
          #4 har:///usr/bin/phive/src/commands/install/InstallCommand.php(63): PharIo\Phive\InstallService->execute()
          #5 har:///usr/bin/phive/src/commands/install/InstallCommand.php(51): PharIo\Phive\InstallCommand->installRequestedPhar()
          #6 har:///usr/bin/phive/src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #7 har:///usr/bin/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #8 usr/bin/phive(306): PharIo\Phive\Cli\Runner->run()
          #9 {main}

          Environment: PHP 7.2.10-0ubuntu0.18.04.1
          Phive Version: 0.12.0

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
 

```

**Comment by theseer** [comment]
The reason other phars work is related to the fact that phing as one of the very few projects already supplies a manifest.xml within the phar, specifying the php version requirement. Our Code sadly failed (or seemingly still does) to parse the mangled Ubuntu PHP version number to run this comparison. It's not phing's fault or their version identifier.

@sebastianheuer Didn't we already fix that?

**Comment by theseer** [comment]
Obviously we didn't:

```
[ERROR]   An error occurred while processing your request:

          Version string '7.3.0RC6' does not follow SemVer semantics
          
          #0 vendor/phar-io/version/src/Version.php(168)
          #1 vendor/phar-io/version/src/Version.php(43): PharIo\Version\Version->ensureVersionStringIsValid()
          #2 src/services/phar/CompatibilityService.php(53): PharIo\Version\Version->__construct()
          #3 src/services/phar/InstallService.php(69): PharIo\Phive\CompatibilityService->canRun()
          #4 src/commands/install/InstallCommand.php(63): PharIo\Phive\InstallService->execute()
          #5 src/commands/install/InstallCommand.php(51): PharIo\Phive\InstallCommand->installRequestedPhar()
          #6 src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #7 src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #8 phive(54): PharIo\Phive\Cli\Runner->run()
          #9 {main}

          Environment: PHP 7.3.0RC6
          Phive Version: 0.12.0-6-ga563fea-dirty

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by theseer** [comment]
@sebastianheuer Can you roll a new release on monday?

**Comment by jawira** [comment]
ok, that was fast... :+1:
