### ISSUE TITLE
"phive install phpunit" throws Exception

### ISSUE THREAD

**Issue by mihaeu** [phar-io/phive#174]
Hi,

I just got this exception with a fresh install of phive and a fairly up to date version of PHP:

```
phive install phpunit
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phpunit-7.4.4.phar
Downloading https://phar.phpunit.de/phpunit-7.4.4.phar.asc
Downloading key 4AA394086372C20A
Trying hkps.pool.sks-keyservers.net (46.4.246.179)
Successfully downloaded key
[ERROR]    An error occurred while processing your request:

          Call to a member function format() on null
          
          #0 har:///usr/bin/phive/src/services/key/PublicKey.php(68)
          #1 har:///usr/bin/phive/src/services/key/KeyService.php(69): PharIo\Phive\PublicKey->getInfo()
          #2 har:///usr/bin/phive/src/services/signature/gpg/GnupgSignatureVerifier.php(40): PharIo\Phive\KeyService->importKey()
          #3 har:///usr/bin/phive/src/services/phar/PharDownloader.php(109): PharIo\Phive\GnupgSignatureVerifier->verify()
          #4 har:///usr/bin/phive/src/services/phar/PharDownloader.php(61): PharIo\Phive\PharDownloader->verifySignature()
          #5 har:///usr/bin/phive/src/services/phar/PharService.php(38): PharIo\Phive\PharDownloader->download()
          #6 har:///usr/bin/phive/src/services/phar/InstallService.php(68): PharIo\Phive\PharService->getPharFromRelease()
          #7 har:///usr/bin/phive/src/commands/install/InstallCommand.php(57): PharIo\Phive\InstallService->execute()
          #8 har:///usr/bin/phive/src/commands/install/InstallCommand.php(44): PharIo\Phive\InstallCommand->installRequestedPhar()
          #9 har:///usr/bin/phive/src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #10 har:///usr/bin/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #11 usr/bin/phive(300): PharIo\Phive\Cli\Runner->run()
          #12 {main}

          Environment: PHP 7.2.7
          Phive Version: 0.10.0

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

That should be most of the info, but somehow it feels like I'm missing something. Ran `phive install phing` just before that and it worked.

Giving another talk at the PHP UG Munich about (among other tools) Phive by the way ;)

**Comment by mihaeu** [comment]
Ok never mind ... had an old phive version in `/usr/bin/` and the new one installed to `/usr/local/bin/` ...

Still can't install, but this time it's the key server.

```
phive install phpunit
Phive 0.12.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phpunit-7.4.4.phar
Downloading https://phar.phpunit.de/phpunit-7.4.4.phar.asc
Downloading key 4AA394086372C20A
Trying hkps.pool.sks-keyservers.net (46.4.246.179)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
Trying hkps.pool.sks-keyservers.net (37.191.231.105)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
Trying hkps.pool.sks-keyservers.net (192.146.137.99)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
Trying hkps.pool.sks-keyservers.net (192.146.137.98)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::99:0)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
Trying hkps.pool.sks-keyservers.net (2a01:4f8:222:2401:1::179)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::98:0)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error 
[ERROR]    PublicKey 4AA394086372C20A not found on key servers 
```

**Comment by theseer** [comment]
The instability of the key servers is starting to become a serious problem.
One more reason to implement #158.
