### ISSUE TITLE
Phive crashes if a downloaded signature file is not a signature file

### ISSUE THREAD

**Issue by theseer** [phar-io/phive#180]
```
theseer@nyda /tmp $ phive install phpbench
Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpbench/phpbench/releases
Downloading https://github.com/phpbench/phpbench/releases/download/0.16.4/phpbench.phar
Downloading https://github.com/phpbench/phpbench/releases/download/0.16.4/phpbench.phar.asc
[ERROR]   An error occurred while processing your request:

          Argument 1 passed to PharIo\Phive\GnupgVerificationResult::__construct() must be of the type array, null given, called in phar:///home/theseer/storage/php/phar.io/phive/phive/src/services/signature/gpg/GnupgSignatureVerifier.php on line 61
          
          #0 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/signature/gpg/GnupgVerificationResult.php(14)
          #1 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/signature/gpg/GnupgSignatureVerifier.php(61): PharIo\Phive\GnupgVerificationResult->__construct()
          #2 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/signature/gpg/GnupgSignatureVerifier.php(38): PharIo\Phive\GnupgSignatureVerifier->attemptVerification()
          #3 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/phar/PharDownloader.php(109): PharIo\Phive\GnupgSignatureVerifier->verify()
          #4 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/phar/PharDownloader.php(61): PharIo\Phive\PharDownloader->verifySignature()
          #5 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/phar/PharService.php(38): PharIo\Phive\PharDownloader->download()
          #6 har:///home/theseer/storage/php/phar.io/phive/phive/src/services/phar/InstallService.php(68): PharIo\Phive\PharService->getPharFromRelease()
          #7 har:///home/theseer/storage/php/phar.io/phive/phive/src/commands/install/InstallCommand.php(63): PharIo\Phive\InstallService->execute()
          #8 har:///home/theseer/storage/php/phar.io/phive/phive/src/commands/install/InstallCommand.php(51): PharIo\Phive\InstallCommand->installRequestedPhar()
          #9 har:///home/theseer/storage/php/phar.io/phive/phive/src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #10 har:///home/theseer/storage/php/phar.io/phive/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #11 home/theseer/storage/php/phar.io/phive/phive(306): PharIo\Phive\Cli\Runner->run()
          #12 {main}

          Environment: PHP 7.3.3
          Phive Version: 0.12.1

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
````

**Comment by villfa** [comment]
I think this issue can be closed: it has been already fixed by https://github.com/phar-io/phive/commit/736bd855#diff-fdfcb0c8fddd09d27b133546d7c24ec09db1c9728ec9810225be5f887d9e2c34

**Comment by theseer** [comment]
Agreed. Thanks for pointing this out.
