### ISSUE TITLE
Error installing behat

### ISSUE THREAD

**Issue by temp** [phar-io/phive#203]
Installing behat/behat with phive 0.12.3 results in an error:

```
# phive install --force-accept-unsigned behat/behat
Phive 0.12.3 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/behat/behat/releases
[WARNING]  behat/behat 3.5.0: No downloadable PHAR
[WARNING]  behat/behat 3.4.3: No downloadable PHAR
[WARNING]  behat/behat 3.4.1: No downloadable PHAR
[WARNING]  behat/behat 3.4.2: No downloadable PHAR
[WARNING]  behat/behat 3.4.0: No downloadable PHAR
[WARNING]  behat/behat 3.3.1: No downloadable PHAR
Downloading https://github.com/Behat/Behat/releases/download/v3.3.0/behat.phar
PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, bool given in phar:///usr/local/bin/phive/src/shared/cli/Runner.php:103
Stack trace:
#0 phar:///usr/local/bin/phive/src/shared/cli/Runner.php(68): PharIo\Phive\Cli\Runner->showErrorWithTrace('file_put_conten...', 'phar:///usr/loc...', 36, Array)
#1 /usr/local/bin/phive(312): PharIo\Phive\Cli\Runner->run()
#2 {main}
  thrown in phar:///usr/local/bin/phive/src/shared/cli/Runner.php on line 103
PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, bool given in phar:///usr/local/bin/phive/src/shared/cli/Runner.php:103
Stack trace:
#0 phar:///usr/local/bin/phive/src/shared/cli/Runner.php(99): PharIo\Phive\Cli\Runner->showErrorWithTrace('Uncaught TypeEr...', 'phar:///usr/loc...', 103, Array)
#1 [internal function]: PharIo\Phive\Cli\Runner->shutdownHandler()
#2 {main}
  thrown in phar:///usr/local/bin/phive/src/shared/cli/Runner.php on line 103
```

PHP version is 7.3.6 from alpine.

**Comment by theseer** [comment]
Confirmed and Investigating.

**Comment by eclipxe13** [comment]
looks that this issue also appears with any other package using "vendor/project" like:

```
phive install macfja/pharbuilder
phive install vimeo/psalm
```

Both end with:

```
PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, bool given in phar:///usr/local/bin/phive/src/shared/cli/Runner.php:103
Stack trace:
#0 phar:///usr/local/bin/phive/src/shared/cli/Runner.php(68): PharIo\Phive\Cli\Runner->showErrorWithTrace('file_put_conten...', 'phar:///usr/loc...', 36, Array)
#1 /usr/local/bin/phive(312): PharIo\Phive\Cli\Runner->run()
#2 {main}
  thrown in phar:///usr/local/bin/phive/src/shared/cli/Runner.php on line 103
PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, bool given in phar:///usr/local/bin/phive/src/shared/cli/Runner.php:103
Stack trace:
#0 phar:///usr/local/bin/phive/src/shared/cli/Runner.php(99): PharIo\Phive\Cli\Runner->showErrorWithTrace('Uncaught TypeEr...', 'phar:///usr/loc...', 103, Array)
#1 [internal function]: PharIo\Phive\Cli\Runner->shutdownHandler()
#2 {main}
  thrown in phar:///usr/local/bin/phive/src/shared/cli/Runner.php on line 103
```

**Comment by kolaente** [comment]
But it also does not work for me when trying a package without the form `vendor/package`:
```
Step 6/10 : RUN phive install -g --trust-gpg-keys 993876E71CF55503,DD545A4C2E198F79 n98-magerun2
 ---> Running in 0724cb4e6f43
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Phive 0.12.4 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching repository list
Downloading https://phar.io/data/repositories.xml
Downloading https://files.magerun.net/phive.xml
Downloading https://files.magerun.net/n98-magerun2-3.2.0.phar
Downloading https://files.magerun.net/n98-magerun2-3.2.0.phar.asc
Downloading key DD545A4C2E198F79
Trying to connect to keys.openpgp.org (37.218.245.50)
Trying to connect to keys.openpgp.org (2a00:c6c0::154:1:0:0:1)
[ERROR]   Request failed:  (while requesting https://keys.openpgp.org/pks/lookup?search=0xDD545A4C2E198F79&op=index&options=mr)
[WARNING] Failed with error code 0: No mirror yielded any result. Giving up.
Trying to connect to keys.fedoraproject.org (140.211.169.207)
Downloading https://keys.fedoraproject.org/pks/lookup?search=0xDD545A4C2E198F79&op=index&options=mr
Trying to connect to keys.fedoraproject.org (140.211.169.207)
Downloading https://keys.fedoraproject.org/pks/lookup?search=0xDD545A4C2E198F79&op=get&options=mr
Successfully downloaded key

	Fingerprint: 1531 6BB4 47A1 AB42 858E DB65 DD54 5A4C 2E19 8F79

	Christian Muench <c.muench@netz98.de> (2018-12-02)

	Created: 2018-12-02

Copying n98-magerun2-3.2.0.phar to /usr/local/bin/n98-magerun2

PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, boolean given in phar:///usr/bin/phive/src/shared/cli/Runner.php:103
Stack trace:
#0 phar:///usr/bin/phive/src/shared/cli/Runner.php(99): PharIo\Phive\Cli\Runner->showErrorWithTrace('Module 'imagick...', 'Unknown', 0, Array)
#1 [internal function]: PharIo\Phive\Cli\Runner->shutdownHandler()
#2 {main}
  thrown in phar:///usr/bin/phive/src/shared/cli/Runner.php on line 103
The command '/bin/sh -c phive install -g --trust-gpg-keys 993876E71CF55503,DD545A4C2E198F79 n98-magerun2' returned a non-zero code: 255
```

**Comment by kolaente** [comment]
It even throws the error when showing the version:
```
Step 6/12 : RUN phive --version
 ---> Running in 1945a1a9783d
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Phive 0.12.4 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors

PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, boolean given in phar:///usr/bin/phive/src/shared/cli/Runner.php:103
Stack trace:
#0 phar:///usr/bin/phive/src/shared/cli/Runner.php(99): PharIo\Phive\Cli\Runner->showErrorWithTrace('Module 'imagick...', 'Unknown', 0, Array)
#1 [internal function]: PharIo\Phive\Cli\Runner->shutdownHandler()
#2 {main}
  thrown in phar:///usr/bin/phive/src/shared/cli/Runner.php on line 103
The command '/bin/sh -c phive --version' returned a non-zero code: 255
```
@theseer looks like your fix did not fix it :thinking:

**Comment by kolaente** [comment]
It looks like it works now, I don't really know why, but I suspect a misconfiguration in out base image. Strange...

**Comment by theseer** [comment]
Interesting catch and a 'funny' cascade of issues.

The core problem lies in the `PHP Warning:  Module 'imagick' already loaded in Unknown on line 0` in combination with our shutdown handler, which is looking for warnings to report - as our code is supposed to be running without warnings.

So I'd assume installing actually worked just fine but due to the misconfiguration of PHP (as in not being able to load imagick twice and the warning being generated from that) phive believes an error occurred.

The shutdown handler tries to render the error and tries to resolve the path of the file the error occurred it. As that file is `Unknown` the realpath call fails, making it return false which - due to strict types - strlen doesn't like and so phive crashes.
