### ISSUE TITLE
Fatal (shoudl not happen) error running `phive install`

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#225]
```console
An error occurred while processing your request:

          file_get_contents(/Users/Aerendir/.phive/phars/php-cs-fixer.phar): failed to open stream: No such file or directory
          
          #0 src/shared/PharRegistry.php(214)
          #1 unknown file(0): PharIo\Phive\Cli\Runner->errorHandler()
          #2 src/shared/PharRegistry.php(214): file_get_contents()
          #3 src/shared/PharRegistry.php(209): PharIo\Phive\PharRegistry->loadPharFile()
          #4 src/shared/PharRegistry.php(59): PharIo\Phive\PharRegistry->nodetoPhar()
          #5 src/shared/repository/LocalRepository.php(18): PharIo\Phive\PharRegistry->getPhars()
          #6 src/services/resolver/LocalAliasResolver.php(22): PharIo\Phive\LocalRepository->getReleasesByRequestedPhar()
          #7 src/services/resolver/RequestedPharResolverService.php(23): PharIo\Phive\LocalAliasResolver->resolve()
          #8 src/commands/install/InstallCommand.php(53): PharIo\Phive\RequestedPharResolverService->resolve()
          #9 src/commands/install/InstallCommand.php(42): PharIo\Phive\InstallCommand->resolveToRelease()
          #10 src/commands/install/InstallCommand.php(37): PharIo\Phive\InstallCommand->installRequestedPhar()
          #11 src/shared/cli/Runner.php(193): PharIo\Phive\InstallCommand->execute()
          #12 src/shared/cli/Runner.php(60): PharIo\Phive\Cli\Runner->execute()
          #13 (313): PharIo\Phive\Cli\Runner->run()
          #14 {main}

          Environment: PHP 7.2.9
          Phive Version: 0.13.2

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!

```

The only "strange" thing I did was run `phive purge`:

```console
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Phar php-cs-fixer 2.12.2 has been deleted.
Phar phan 1.2.5 has been deleted.
Phar phan 2.4.6 has been deleted.
Phar psalm 3.8.2 has been deleted.
Phar psalm 3.5.3 has been deleted.
Phar psalm 3.4.12 has been deleted.
Phar phpstan 0.12.8 has been deleted.
```

**Comment by Aerendir** [comment]
To "solve" the issue I've simply emptied the folder `.phive`: this makes Phive start again with download of keys and PHARs.

**Comment by MacFJA** [comment]
It look like you upgrade from an old version of Phive (from at least 0.12.2).

In the old version of Phive, you can't have several version of the same tool (#202), the latest one override the existing one (same saving path). In later version of Phive, the version number is added to the saved Phar binary to prevent that (introduced in [0.12.3](https://github.com/phar-io/phive/releases/tag/0.12.3))

In your case I suppose that you have 2 versions of the same tool, one being used, the other not. So when you `purge` unused Phar it remove the Phar of the unused version, but as they share the same path, the used version was "also removed".
And during the `install` you request this tool (so `php-cs-fixer`, `phan`, `psalm` or `phpstan`) and Phive fail to build its list of already downloaded Phars

**Comment by theseer** [comment]
I agree with @MacFJA's assessment, as embarrassing as the overwriting bug was..

I'll close this, as I don't believe there's anything left to do here.
Please comment, in case that's wrong.

@MacFJA Thanks for looking into it!
