### ISSUE TITLE
Crappy connection results in type error

### ISSUE THREAD

**Issue by webmaster777** [phar-io/phive#226]
While updating with a crappy connection (train wifi w/ probably some 3g/4g router as backend while going through a rural area), the following error occured:

```
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpstan/phpstan/releases
Downloading https://github.com/phpstan/phpstan/releases/download/0.12.9/phpstan.phar
 ╰|======================>                 | 9.53 MB / 16.84 MB -  57%[ERROR]    An error occurred while processing your request:

          Argument 2 passed to PharIo\Phive\HttpResponse::__construct() must be of the type string, bool given, called in phar:///Users/mkroese/path/phive/src/shared/http/CurlHttpClient.php on line 132
          
          #0 src/shared/http/HttpResponse.php(18)
          #1 src/shared/http/CurlHttpClient.php(132): PharIo\Phive\HttpResponse->__construct()
          #2 src/shared/http/CurlHttpClient.php(57): PharIo\Phive\CurlHttpClient->execRequest()
          #3 src/shared/http/RetryingHttpClient.php(53): PharIo\Phive\CurlHttpClient->get()
          #4 src/shared/http/RetryingHttpClient.php(46): PharIo\Phive\RetryingHttpClient->doTry()
          #5 src/services/phar/PharDownloader.php(56): PharIo\Phive\RetryingHttpClient->get()
          #6 src/services/phar/PharDownloader.php(36): PharIo\Phive\PharDownloader->downloadFile()
          #7 src/services/phar/PharService.php(22): PharIo\Phive\PharDownloader->download()
          #8 src/services/phar/InstallService.php(45): PharIo\Phive\PharService->getPharFromRelease()
          #9 src/commands/update/UpdateCommand.php(42): PharIo\Phive\InstallService->execute()
          #10 src/shared/cli/Runner.php(193): PharIo\Phive\UpdateCommand->execute()
          #11 src/shared/cli/Runner.php(60): PharIo\Phive\Cli\Runner->execute()
          #12 (313): PharIo\Phive\Cli\Runner->run()
          #13 {main}

          Environment: PHP 7.3.14
          Phive Version: 0.13.2

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by theseer** [comment]
That looks like our curl handling code can't properly deal with not just only a crappy connection but one that makes the transfer die off.

This clearly qualifies as a bug.
