### ISSUE TITLE
implode(): Invalid arguments passed

### ISSUE THREAD

**Issue by peter279k** [phar-io/phive#246]
# Reproducing issue
- Download and verify Phive:
```
wget -O phive.phar "https://phar.io/releases/phive.phar"
wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
gpg --verify phive.phar.asc phive.phar
rm phive.phar.asc
chmod +x phive.phar
```
- Phive version: `0.13.2`
- Install some executable Phar builds via following commands:
```
./phive.phar --no-progress --home ./.phive install --trust-gpg-keys 4AA394086372C20A,31C7E470E2138192,8E730BA25823D8B5,CF1A108D0E7AE720 --force-accept-unsigned
```

## Expected
- There's no error during above command excuting.

## Actual
- The error message is as follows:

```
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Copying phpunit-8.5.2.phar to ./tools/phpunit
Downloading https://squizlabs.github.io/PHP_CodeSniffer/phars/phpcs-3.5.4.phar
Downloading https://squizlabs.github.io/PHP_CodeSniffer/phars/phpcs-3.5.4.phar.asc
Copying phpcs-3.5.4.phar to ./tools/phpcs
Downloading https://github.com/phpstan/phpstan/releases/download/0.12.9/phpstan.phar
Downloading https://github.com/phpstan/phpstan/releases/download/0.12.9/phpstan.phar.asc
Downloading key CF1A108D0E7AE720
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0xCF1A108D0E7AE720
Successfully downloaded key.

	Fingerprint: D326 80D5 957D C711 6BE2 9C14 CF1A 108D 0E7A E720

	Ondrej Mirtes <ondrej@mirtes.cz>

	Created: 2019-12-09

[ERROR]    An error occurred while processing your request:

          implode(): Invalid arguments passed
          
          #0 src/services/signature/gpg/GnupgVerificationResult.php(27)
          #1 unknown file(0): PharIo\Phive\Cli\Runner->errorHandler()
          #2 src/services/signature/gpg/GnupgVerificationResult.php(27): implode()
          #3 src/services/phar/PharDownloader.php(90): PharIo\Phive\GnupgVerificationResult->getStatusMessage()
          #4 src/services/phar/PharDownloader.php(44): PharIo\Phive\PharDownloader->verifySignature()
          #5 src/services/phar/PharService.php(22): PharIo\Phive\PharDownloader->download()
          #6 src/services/phar/InstallService.php(45): PharIo\Phive\PharService->getPharFromRelease()
          #7 src/commands/install/InstallCommand.php(45): PharIo\Phive\InstallService->execute()
          #8 src/commands/install/InstallCommand.php(37): PharIo\Phive\InstallCommand->installRequestedPhar()
          #9 src/shared/cli/Runner.php(193): PharIo\Phive\InstallCommand->execute()
          #10 src/shared/cli/Runner.php(60): PharIo\Phive\Cli\Runner->execute()
          #11 (313): PharIo\Phive\Cli\Runner->run()
          #12 {main}

          Environment: PHP 7.3.17-1+ubuntu18.04.1+deb.sury.org+1
          Phive Version: 0.13.2

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

After tracing error message output, I think the problematic code snippets are as follows:

https://github.com/phar-io/phive/blob/e75aa29de010ec25f12afcbe242fc2072284f066/src/services/signature/gpg/GnupgVerificationResult.php#L27

And the `$this->verificationData['status']` variable may not be array type.

To resolve this issue, I think it should casting the `$this->verificationData['status']` variable to `array` type before doing implode function call.

**Comment by peter279k** [comment]
And my `phive.xml` is as follows:

```xml
?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="phpunit" version="7.3" installed="7.3.5" location="./tools/phpunit" copy="false"/>
  <phar name="phpcs" version="^3.5.2" installed="3.5.4" location="./tools/phpcs" copy="true"/>
  <phar name="phpstan" version="^0.12.2" installed="0.12.9" location="./tools/phpstan" copy="true"/>
</phive>

```

**Comment by peter279k** [comment]
To dig this issue, I also use development repository and add some output functions before making `implode` function call.

```php
.......
    public function getStatusMessage(): string {
        var_dump(gettype($this->verificationData['status']));
        var_dump($this->verificationData['status']);

        return \implode("\n", $this->verificationData['status']);
    }

.......
```

After I use the repository on `master` development branch, I found `$this->verificationData['status']` variable is as follows:

```
/path/to/phive/src/services/signature/gpg/GnupgVerificationResult.php:27:
string(7) "integer"
/path/to/phive/src/services/signature/gpg/GnupgVerificationResult.php:28:
int(9)

```

**Comment by theseer** [comment]
Thanks for the report. It took me a while to reproduce this. It seems like this only happens with `ext/gnupg` installed.

Your fix though is not addressing the underlying issue. The problem seems to lay in our wrapper implementation which deviates from the `ext/gnugpg` results:

__Our Wrapper__:

```php
array(1) {
  [0]=>
  array(5) {
    ["fingerprint"]=>
    string(16) "4AA394086372C20A"
    ["validity"]=>
    int(0)
    ["timestamp"]=>
    string(10) "1536419702"
    ["status"]=>
    array(3) {
      [0]=>
      string(15) "[GNUPG:] NEWSIG"
      [1]=>
      string(55) "[GNUPG:] ERRSIG 4AA394086372C20A 1 10 00 1536419702 9 -"
      [2]=>
      string(35) "[GNUPG:] NO_PUBKEY 4AA394086372C20A"
    }
    ["summary"]=>
    int(128)
  }
}
```

__`ext/gnupg`__:

```php
array(1) {
  [0]=>
  array(5) {
    ["fingerprint"]=>
    string(16) "4AA394086372C20A"
    ["validity"]=>
    int(0)
    ["timestamp"]=>
    int(1536419702)
    ["status"]=>
    int(9)
    ["summary"]=>
    int(128)
  }
}
```

Apart from the maybe non obvious type confusion for the timestamp, the status element is completely wrong. This clearly qualifies as a bug. But not in `phive` but the [gnupg wrapper](https://github.com/phar-io/gnupg). I'll open/move this issue over to it.
