### ISSUE TITLE
Make phive compatible with Xdebug 3.0

### ISSUE THREAD

**Issue by sebastianfeldmann** [phar-io/phive#284]
As mentioned in this tweet
https://twitter.com/icanhazstring/status/1320031880020959235?s=20

The function `xdebug_disable()` will no longer be available in Xdebug 3

https://github.com/phar-io/phive/blob/736bd855e37780d5ea8801bfad082a8176f714f8/src/shared/environment/Environment.php#L127

**Comment by theseer** [comment]
PR #285 merged.

Will be in the next release.

**Comment by sebastianbergmann** [comment]
Please roll a new release:
```
phive           
[ERROR]   An error occurred while processing your request:

          Call to undefined function PharIo\Phive\xdebug_disable()
          
          #0 src/shared/environment/Environment.php(127)
          #1 src/shared/environment/Environment.php(85): PharIo\Phive\Environment->disableXDebug()
          #2 src/shared/cli/Runner.php(172): PharIo\Phive\Environment->ensureFitness()
          #3 src/shared/cli/Runner.php(67): PharIo\Phive\Cli\Runner->ensureFitness()
          #4 (349): PharIo\Phive\Cli\Runner->run()
          #5 {main}

          Environment: PHP 7.4.13 (on Linux 5.9.10-200.fc33.x86_64)
          Phive Version: 0.14.4

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```
