### ISSUE TITLE
Notice when running phive

### ISSUE THREAD

**Issue by mattsches** [phar-io/phive#35]
I just installed phive and ran it for the first time. It seems to work, but I'm getting a notice:

```
$ ./phive.phar 
Phive 0.1.0 - Copyright (C) 2015 by Arne Blankerts and Sebastian Heuer

PHP Notice:  Undefined index: _ in phar:///home/mattsches/bin/phive/phive.phar/src/shared/Environment.php on line 66
PHP Stack trace:
PHP   1. {main}() /home/mattsches/bin/phive/phive.phar:0
PHP   2. TheSeer\CLI\Runner->run() /home/mattsches/bin/phive/phive.phar:106
PHP   3. PharIo\Phive\HelpCommand->execute() phar:///home/mattsches/bin/phive/phive.phar/vendor/theseer/cli/src/Runner.php:18
PHP   4. PharIo\Phive\Environment->getBinaryName() phar:///home/mattsches/bin/phive/phive.phar/src/commands/help/HelpCommand.php:36
[...]
```

```
$ php -v
PHP 5.6.11-1ubuntu3.1 (cli) 
```

No time to look into the code right now, sorry :(

**Comment by theseer** [comment]
Thanks for the report. Can you verify if the problem persists when using the current master state? The code changed quite a lot since the 0.1.0 release and we're about to release 0.2.0.

**Comment by mattsches** [comment]
Just cloned the current master, unfortunately the problem is still there:
```
$ git clone https://github.com/phar-io/phive.git
$ cd phive
$ ./phive 
Phive 0.1.0-85-g87e365c - Copyright (C) 2015-2016 by Arne Blankerts, Sebastian Heuer and Contributors

[ERROR]   An error occured while processing your request:

          Undefined index: _
          
          #0 src/shared/Environment.php(63)
          #1 src/shared/Environment.php(63): PharIo\Phive\Cli\Runner->errorHandler()
          #2 src/commands/help/HelpCommand.php(37): PharIo\Phive\Environment->getBinaryName()
          #3 src/shared/cli/Runner.php(51): PharIo\Phive\HelpCommand->execute()
          #4 phive(55): PharIo\Phive\Cli\Runner->run()
          #5 {main}

          Environment: PHP 5.6.11-1ubuntu3.1
          Phive Version: 0.1.0-85-g87e365c

          This should not have happend and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by theseer** [comment]
Thanks for verifying.

**Comment by theseer** [comment]
Can you quickly verify if that fixes it for you as well?

**Comment by mattsches** [comment]
All looking good now, thanks!
