### ISSUE TITLE
PHP 8.4 deprecation error

### ISSUE THREAD

**Issue by sebastianfeldmann** [phar-io/phive#438]
```
Phive 0.15.2 - Copyright (C) 2015-2024 by Arne Blankerts, Sebastian Heuer and Contributors

Error: [ERROR]   An error occurred while processing your request:
    PharIo\Phive\XmlFile::query(): Implicitly marking parameter $ctx as nullable is deprecated, the explicit nullable type must be used instead
          
    #0 src/shared/XmlFile.php(71)
    #1 (347): PharIo\Phive\Cli\Runner->errorHandler()
    #2 (347): require()
    #3 src/Factory.php(438): {closure:/home/runner/work/captainhook/captainhook/tools/phive:27}()
    #4 src/Factory.php(97): PharIo\Phive\Factory->getPhiveXmlConfig()
    #5 src/commands/CommandLocator.php(42): PharIo\Phive\Factory->getInstallCommand()
    #6 src/shared/cli/Runner.php(241): PharIo\Phive\CommandLocator->getCommand()
    #7 src/shared/cli/Runner.php(95): PharIo\Phive\Cli\Runner->execute()
    #8 (354): PharIo\Phive\Cli\Runner->run()
    #9 {main}
    Environment: PHP 8.4.0-dev (on Linux 6.5.0-1025-azure)
    Phive Version: 0.15.2
    This should not have happened and is most likely a bug.
    Please report it at https://github.com/phar-io/phive/issues, make sure you include
    the full output of this error message. Thank you!
Error: [ERROR]   An error occurred while processing your request:
    PharIo\Phive\Config::__construct(): Implicitly marking parameter $now as nullable is deprecated, the explicit nullable type must be used instead
          
    #0 src/shared/config/Config.php(34)
    #1 unknown file(0): PharIo\Phive\Cli\Runner->shutdownHandler()
    #2 {main}
    Environment: PHP 8.4.0-dev (on Linux 6.5.0-1025-azure)
    Phive Version: 0.15.2
    This should not have happened and is most likely a bug.
    Please report it at https://github.com/phar-io/phive/issues, make sure you include
    the full output of this error message. Thank you!
Error: Process completed with exit code 10.
```

### The problem is here:

https://github.com/phar-io/phive/blob/9dee3083e1c3c725da498a0a0c34bb8db40762f3/src/shared/XmlFile.php#L71

And I think here as well
https://github.com/phar-io/phive/blob/9dee3083e1c3c725da498a0a0c34bb8db40762f3/src/shared/config/Config.php#L36
and here and following
https://github.com/phar-io/phive/blob/9dee3083e1c3c725da498a0a0c34bb8db40762f3/src/shared/phar/ConfiguredPhar.php#L39

### ⚠️  But I'm not sure this is an actual problem ⚠️ 

Because if I understand the RFC correctly using `?Type $var = null` should be the actual fix for the deprecation `Type $var = null`. But maybe I did not get it :/
So it could be a dev version issue and actually a problem with PHP

**Comment by theseer** [comment]
Please try using the current version of phive first and report the result.

**Comment by sebastianfeldmann** [comment]
I was just too stupid to realize that it was fixed in the latest version and only broken in the one I had.

As you said, too late and too many projects

Nevertheless ignoring deprecations if they occur is still a valid point, so nobody has to wait for a new build because of deprecations.

Sorry for this one ;)
